#cloud-config
apt_update: true
apt_upgrade: true

packages:
  - docker.io

runcmd:
  - docker pull tristaaan/acc-worker
  - docker swarm join --token $docker_token $ip:2377

final_message: "The system is finally up"
